# Generated by Django 4.1.7 on 2023-04-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_rename_cars_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='dis',
            field=models.CharField(max_length=200),
        ),
    ]
