# Generated by Django 4.1.7 on 2023-04-17 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_car_image_alter_car_dis_alter_car_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='dis',
            new_name='distance',
        ),
    ]
