# Generated by Django 4.1.7 on 2023-05-04 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_user_reservation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='citty',
            new_name='city',
        ),
    ]
