# Generated by Django 4.1.7 on 2023-05-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_rename_citty_user_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
